In [1]:
import pandas as pd
import numpy as np

In [2]:
input_filepath = 'Dati.xlsx'

## Produzioni

Per cartellino (ricetta)

In [3]:
prod_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Produzioni"
)
prod_df_raw.head()

   Articolo                         Descrizione  lega  Cartellino    Quantita
0  BIL01330   Billette Euro-HS Diam. 330 CW617N     1           9  18962193.5
1  BIL02210         Billette Prf.Stp. Diam. 210     2           2     36759.3
2  BIL02330  Billette Prf.Stp. Diam. 330 CW612N     2           2   3682923.8
3  BIL04210           Billette MS Pb2 Diam. 210     4           9     10405.8
4  BIL04330    Billette MS Pb2 Diam. 330 CW617N     4           9    990259.7

In [4]:
prod_df = prod_df_raw[['Cartellino', 'Quantita']].groupby('Cartellino').sum().sort_values(['Cartellino']).reset_index()
prod_df

   Cartellino    Quantita
0           2   5798032.3
1           7  34993167.0
2           8   7480845.3
3           9  93250827.7
4          14   3751759.6
5          15   1358532.7
6          18    200887.2
7          19   1570139.9
8          28   5013209.2
9          38    285859.1

In [5]:
produzioni = np.array(prod_df['Quantita'])
print(produzioni.shape)
produzioni

(10,)

array([ 5798032.3, 34993167. ,  7480845.3, 93250827.7,  3751759.6,
        1358532.7,   200887.2,  1570139.9,  5013209.2,   285859.1])

## Consumi

Per famiglia

In [6]:
cons_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Consumi"
)
cons_df_raw.head()

,Codice,Gruppo m,Famiglia,Quantità,Codice Materiale,Verifica se il materiale è stato rilevato
0,MP02501,MP140,12,-5380.0,NaN,12
1,MP02508,MP160,13,-8846.0,NaN,13
2,MP02509,MP140,12,-653965.0,NaN,12
3,MP02514,MP166,14,-6542.0,NaN,14
4,MP02515,MP155,15,-7392.0,NaN,15

In [7]:
cons_df = cons_df_raw[['Famiglia', 'Quantità']].groupby('Famiglia').sum().sort_values(['Quantità']).sort_values(['Famiglia']).reset_index()
cons_df['Quantità'] = cons_df['Quantità']*-1
cons_df

    Famiglia      Quantità
0          1  1.247382e+06
1          2  7.459129e+07
2          3  3.147928e+06
3          4  1.607647e+06
4          5  7.026350e+04
5          7  7.182773e+05
6          9  2.362700e+04
7         11  3.362200e+05
8         12  4.153406e+07
9         13  2.394889e+06
10        14  1.419232e+06
11        15  4.850986e+05
12        17  3.388871e+05
13        19  2.745870e+04
14        20  2.418290e+06
15        31  1.175428e+07
16        35  3.837550e+05
17        41  5.173973e+06
18        42  1.041021e+07
19        51  1.486227e+06
20        52  5.788200e+04
21        56  2.350000e+03
22        57  4.442000e+03
23        60  1.220500e+04
24        61  2.432700e+04
25        62  2.130000e+02
26        71  6.395500e+03
27        72  1.084300e+04

In [8]:
consumi = np.array(cons_df['Quantità'])
print(consumi.shape)
np.sum(consumi)
consumi

(28,)

array([1.24738200e+06, 7.45912877e+07, 3.14792787e+06, 1.60764660e+06,
       7.02635000e+04, 7.18277300e+05, 2.36270000e+04, 3.36220000e+05,
       4.15340593e+07, 2.39488900e+06, 1.41923230e+06, 4.85098600e+05,
       3.38887100e+05, 2.74587000e+04, 2.41829000e+06, 1.17542770e+07,
       3.83755000e+05, 5.17397300e+06, 1.04102070e+07, 1.48622700e+06,
       5.78820000e+04, 2.35000000e+03, 4.44200000e+03, 1.22050000e+04,
       2.43270000e+04, 2.13000000e+02, 6.39550000e+03, 1.08430000e+04])

## Cartellino standard (ricetta)

In [9]:
cart_df_raw = pd.read_excel(
    input_filepath,
    sheet_name="Cartellino Standard"
)

cart_df_raw = cart_df_raw[cart_df_raw['Cartellino'].isin(prod_df['Cartellino'])]
cart_df_raw = cart_df_raw[cart_df_raw['Famiglia'].isin(cons_df['Famiglia'])]

cart_df_raw

     Cartellino  Famiglia        Descrizione famiglia  Percentuale
0             9       1.0          Rottame ott. misto          0.0
1             9       2.0          Tornitura Euro/pb3         41.5
2             9      12.0    Sfridi/Spezzoni Euro/Pb3         28.4
3             9      20.0                Pani Ot Euro          3.0
4             9      42.0                        Rame         23.8
..          ...       ...                         ...          ...
175          38      31.0                       Zinco         32.0
176          38      60.0               Prolega CU-SI         10.0
178          38      56.0                Prolega CU-P          0.2
179          38      19.0      Sfrdi/Spezzoni SIBRASS          1.0
180          38       4.0  Tornitura LFB-CZLL-OT60/40          NaN

[95 rows x 4 columns]

In [10]:
cart_df = cart_df_raw[['Cartellino', 'Famiglia', 'Percentuale']].reset_index().pivot_table(
    index=['Famiglia'],
    columns=['Cartellino'],
    values='Percentuale'
).fillna(0)

print(cart_df.shape)
cart_df

(28, 10)

Cartellino    2     7     8      9     14    15    18     19     28    38
Famiglia
1.0          0.0   3.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   0.0
2.0         46.0  45.0   5.0  41.50   0.0   0.0   0.0   0.00   1.90   0.0
3.0          0.0   0.0  28.6   0.00   0.0   0.0   0.0   0.00   0.00   0.0
4.0          0.0   0.0   0.0   0.00  40.0   0.0   0.0   0.00  40.00   0.0
5.0          0.0   0.0   0.0   0.00   0.0  38.0   0.0   0.00   0.00   0.0
7.0          0.0   0.0   0.0   0.00   0.0   0.0   0.0  39.70   0.00   0.0
9.0          0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   1.0
11.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   5.00   0.0
12.0        30.0  21.0   5.0  28.40   0.0   0.0   0.0   0.00   0.50   0.0
13.0         0.0   0.0  30.0   0.00   6.0   2.0   0.0   0.00   0.00   0.0
14.0         0.0   0.0   0.0   0.00  24.9   0.0  83.2  13.75  41.80   0.0
15.0         0.0   0.0   0.0   0.00   0.0  35.7   0.0   0.00   0.00   0.0
17.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0  40.00   0.00   0.0
19.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   0.00   1.0
20.0        10.0  15.0   0.0   3.00   0.0   0.0   0.0   0.00   0.00   0.0
31.0         0.7   0.7   8.5   1.10  10.0   4.0   7.8   2.70   3.20  32.0
35.0         0.0   8.0  15.0   1.02   0.0   7.4   2.0   0.50   0.00   0.0
41.0         0.0   0.0   7.0   0.08   6.3   3.8   6.7   2.40   2.05  55.8
42.0        13.3   7.3   0.0  23.80   0.0   0.0   0.0   0.00   0.00   0.0
51.0         0.0   0.0   0.0   0.00   1.0   0.0   0.0   0.00   0.00   0.0
52.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.00   2.05   0.0
56.0         0.0   0.0   0.0   0.00   0.0   0.0   0.3   0.00   0.00   0.2
57.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.10   0.00   0.0
60.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.10   0.00  10.0
61.0         0.0   0.0   0.9   0.00   1.8   0.4   0.0   0.50   0.00   0.0
62.0         0.0   0.0   0.0   0.00   0.0   0.0   0.0   0.05   0.00   0.0
71.0         0.0   0.0   0.0   0.00  10.0   8.0   0.0   0.00   3.50   0.0
72.0         0.0   0.0   0.0   0.00   0.0   0.7   0.0   0.20   0.00   0.0

In [29]:
ricette = np.array(cart_df).flatten()/100
ricette

array([0.000e+00, 3.000e-02, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 4.600e-01, 4.500e-01,
       5.000e-02, 4.150e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.900e-02, 0.000e+00, 0.000e+00, 0.000e+00, 2.860e-01, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 4.000e-01, 0.000e+00,
       0.000e+00, 0.000e+00, 4.000e-01, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 3.800e-01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 3.970e-01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e-02, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       5.000e-02, 0.000e+00, 3.000e-01, 2.100e-01, 5.000e-02, 2.840e-01,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.000e-03, 0.000e+00,
       0.000e+00, 0.000e+00, 3.000e-01, 0.000e+00, 6.000e-02, 2.000e-02,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 2.490e-01, 0.000e+00, 8.320e-01, 1.375e-01,
       4.180e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 3.570e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 4.000e-01, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 1.000e-02, 1.000e-01, 1.500e-01, 0.000e+00, 3.000e-02,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       7.000e-03, 7.000e-03, 8.500e-02, 1.100e-02, 1.000e-01, 4.000e-02,
       7.800e-02, 2.700e-02, 3.200e-02, 3.200e-01, 0.000e+00, 8.000e-02,
       1.500e-01, 1.020e-02, 0.000e+00, 7.400e-02, 2.000e-02, 5.000e-03,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 7.000e-02, 8.000e-04,
       6.300e-02, 3.800e-02, 6.700e-02, 2.400e-02, 2.050e-02, 5.580e-01,
       1.330e-01, 7.300e-02, 0.000e+00, 2.380e-01, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 1.000e-02, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 2.050e-02, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       3.000e-03, 0.000e+00, 0.000e+00, 2.000e-03, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e-03,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 1.000e-03, 0.000e+00, 1.000e-01,
       0.000e+00, 0.000e+00, 9.000e-03, 0.000e+00, 1.800e-02, 4.000e-03,
       0.000e+00, 5.000e-03, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 5.000e-04,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
       1.000e-01, 8.000e-02, 0.000e+00, 0.000e+00, 3.500e-02, 0.000e+00,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 7.000e-03,
       0.000e+00, 2.000e-03, 0.000e+00, 0.000e+00])

## Composizioni famiglia

In [12]:
comp_raw = pd.read_excel(
    input_filepath,
    sheet_name="Analisi IN FAM",
    header=2
)
comp_raw = comp_raw.drop(columns=["Media di Totale"])
comp_raw = comp_raw[comp_raw['Etichette di riga'].isin(cons_df['Famiglia'])]
comp_raw = comp_raw.set_index('Etichette di riga')
comp_raw.head()

,Media di Cu,Media di Pb,Media di Sn,Media di Fe,Media di Ni,Media di Al,Media di Mn,Media di Si,Media di As,Media di Sb,Media di Cd,Media di altri,Media di Zn
Etichette di riga,,,,,,,,,,,,,
1,60.210,1.830,0.440,0.29,0.340,0.1,0.01,0.01,0.01,0.01,0.01,0.0,36.74
2,58.500,2.055,0.215,0.24,0.080,0.0,0.00,0.00,0.00,0.00,0.00,0.0,38.91
3,61.800,1.720,0.100,0.11,0.040,0.0,0.00,0.00,0.00,0.00,0.00,0.0,36.23
4,60.935,0.195,0.125,0.06,0.015,0.0,0.00,0.00,0.00,0.00,0.00,0.0,38.67
5,63.900,1.300,0.190,0.13,0.060,0.0,0.00,0.00,0.00,0.00,0.00,0.0,34.42

In [13]:
# Indici mancanti
a = np.array(comp_raw.reset_index()['Etichette di riga'])
b = np.array(cart_df.reset_index()['Famiglia']).astype(int)

for i in range(len(b)):
    if (b[i] not in a):
        print(b[i])
        comp_raw = comp_raw.reindex(comp_raw.index.values.tolist()+[b[i]]).fillna(0).sort_index()

In [14]:
composizioni_famiglia = np.array(comp_raw)
print(composizioni_famiglia.shape)
composizioni_famiglia = composizioni_famiglia.flatten()/100
composizioni_famiglia

(28, 13)

array([6.02100000e-01, 1.83000000e-02, 4.40000000e-03, 2.90000000e-03,
       3.40000000e-03, 1.00000000e-03, 1.00000000e-04, 1.00000000e-04,
       1.00000000e-04, 1.00000000e-04, 1.00000000e-04, 0.00000000e+00,
       3.67400000e-01, 5.85000000e-01, 2.05500000e-02, 2.15000000e-03,
       2.40000000e-03, 8.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.89100000e-01, 6.18000000e-01, 1.72000000e-02,
       1.00000000e-03, 1.10000000e-03, 4.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.62300000e-01, 6.09350000e-01,
       1.95000000e-03, 1.25000000e-03, 6.00000000e-04, 1.50000000e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.86700000e-01,
       6.39000000e-01, 1.30000000e-02, 1.90000000e-03, 1.30000000e-03,
       6.00000000e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.44200000e-01, 7.72500000e-01, 1.00000000e-03, 1.00000000e-04,
       5.00000000e-04, 2.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 2.25700000e-01, 6.51000000e-01, 1.00000000e-04,
       1.14000000e-02, 2.00000000e-04, 1.70000000e-03, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.35600000e-01, 2.92500000e-01,
       1.25000000e-02, 7.75000000e-04, 8.75000000e-04, 2.75000000e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.93075000e-01,
       6.17700000e-01, 1.72000000e-02, 9.00000000e-04, 1.00000000e-03,
       3.00000000e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.62900000e-01, 6.04566667e-01, 1.13333333e-03, 9.00000000e-04,
       5.00000000e-04, 1.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.92800000e-01, 6.41000000e-01, 1.30000000e-02,
       1.45000000e-03, 9.50000000e-04, 3.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.43300000e-01, 7.72500000e-01,
       1.00000000e-03, 1.00000000e-04, 5.00000000e-04, 2.00000000e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.25700000e-01,
       5.81400000e-01, 2.54000000e-02, 3.10000000e-03, 3.20000000e-03,
       1.60000000e-03, 2.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.85100000e-01, 6.66666667e-04, 3.80000000e-03, 9.33333333e-04,
       3.00000000e-04, 6.66666667e-05, 5.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 9.93733333e-01, 0.00000000e+00, 9.99000000e-01,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e-03, 4.97500000e-01,
       2.50000000e-04, 2.50000000e-04, 2.50000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 5.01750000e-01,
       9.90000000e-01, 2.35000000e-03, 7.00000000e-04, 7.00000000e-04,
       3.00000000e-04, 1.00000000e-04, 1.00000000e-04, 1.00000000e-04,
       1.00000000e-04, 1.00000000e-04, 1.00000000e-04, 0.00000000e+00,
       5.35000000e-03, 6.80425000e-01, 1.00000000e-04, 0.00000000e+00,
       2.00000000e-04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 3.19275000e-01, 8.50400000e-01, 1.00000000e-04,
       0.00000000e+00, 2.00000000e-04, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.49300000e-01, 1.00000000e-02,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 9.90000000e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       7.00000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       3.00000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 5.00000000e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 5.00000000e-01, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       9.99900000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       9.99000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.00000000e-03,
       8.50000000e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       1.50000000e-01, 9.80000000e-01, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       2.00000000e-02, 0.00000000e+00, 6.51500000e-01, 5.60000000e-03,
       4.00000000e-04, 6.00000000e-04, 2.00000000e-04, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 3.41700000e-01, 6.54700000e-01,
       4.90000000e-03, 4.00000000e-04, 5.00000000e-04, 1.00000000e-04,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.39400000e-01])

## Valore atteso materiale per ricetta

In [15]:
att_raw = pd.read_excel(
    input_filepath,
    sheet_name="Toll Fonderia Medio",
    header=1,
    usecols='A,AA:AM'
)
att_raw = att_raw.loc[att_raw['lega'].isin(prod_df['Cartellino'])]
att_raw = att_raw.set_index('lega')
print(att_raw.shape)
att_raw

(10, 13)

,Cu.2,Pb.2,Sn.2,Fe.2,Ni.2,Al.2,Mn.2,Si.2,As.2,Sb.2,Cd.2,altri.2,Zinco
lega,,,,,,,,,,,,,
2,59.40,2.05,0.165,0.150,0.050,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,38.1325
7,58.00,2.90,0.165,0.165,0.100,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,38.6175
8,61.80,2.00,0.065,0.065,0.050,0.015,0.010,0.005,0.100,0.0075,0.005,0.000,35.8775
9,58.40,2.05,0.165,0.165,0.050,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,39.1175
14,62.50,0.20,0.100,0.065,0.050,0.015,0.010,0.005,0.100,0.0075,0.005,0.001,36.9415
15,63.70,1.40,0.210,0.065,0.050,0.600,0.010,0.005,0.070,0.0075,0.005,0.000,33.8775
18,62.45,0.21,0.100,0.225,0.025,0.015,0.010,0.000,0.010,0.0075,0.005,0.100,36.8425
19,65.00,0.50,0.100,0.050,0.025,0.125,0.010,0.200,0.065,0.0000,0.005,0.001,33.9190
28,58.35,0.20,0.280,0.070,0.050,0.015,0.005,0.005,0.010,0.0050,0.005,0.000,41.0050
38,76.00,0.05,0.150,0.150,0.100,0.025,0.025,3.100,0.000,0.0075,0.005,0.060,20.3275

In [16]:
a = np.array(att_raw.reset_index()['lega'])
b = np.array(prod_df['Cartellino']).astype(int)

for i in range(len(b)):
    if (b[i] not in a):
        print(b[i])
        att_raw = att_raw.reindex(att_raw.index.values.tolist()+[b[i]]).fillna(0).sort_index()

att_raw

,Cu.2,Pb.2,Sn.2,Fe.2,Ni.2,Al.2,Mn.2,Si.2,As.2,Sb.2,Cd.2,altri.2,Zinco
lega,,,,,,,,,,,,,
2,59.40,2.05,0.165,0.150,0.050,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,38.1325
7,58.00,2.90,0.165,0.165,0.100,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,38.6175
8,61.80,2.00,0.065,0.065,0.050,0.015,0.010,0.005,0.100,0.0075,0.005,0.000,35.8775
9,58.40,2.05,0.165,0.165,0.050,0.015,0.010,0.005,0.010,0.0075,0.005,0.000,39.1175
14,62.50,0.20,0.100,0.065,0.050,0.015,0.010,0.005,0.100,0.0075,0.005,0.001,36.9415
15,63.70,1.40,0.210,0.065,0.050,0.600,0.010,0.005,0.070,0.0075,0.005,0.000,33.8775
18,62.45,0.21,0.100,0.225,0.025,0.015,0.010,0.000,0.010,0.0075,0.005,0.100,36.8425
19,65.00,0.50,0.100,0.050,0.025,0.125,0.010,0.200,0.065,0.0000,0.005,0.001,33.9190
28,58.35,0.20,0.280,0.070,0.050,0.015,0.005,0.005,0.010,0.0050,0.005,0.000,41.0050
38,76.00,0.05,0.150,0.150,0.100,0.025,0.025,3.100,0.000,0.0075,0.005,0.060,20.3275

In [17]:
val_att = np.array(att_raw)
print(val_att.shape)
val_att

(10, 13)

array([[5.94000e+01, 2.05000e+00, 1.65000e-01, 1.50000e-01, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.81325e+01],
       [5.80000e+01, 2.90000e+00, 1.65000e-01, 1.65000e-01, 1.00000e-01,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.86175e+01],
       [6.18000e+01, 2.00000e+00, 6.50000e-02, 6.50000e-02, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-01, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.58775e+01],
       [5.84000e+01, 2.05000e+00, 1.65000e-01, 1.65000e-01, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.91175e+01],
       [6.25000e+01, 2.00000e-01, 1.00000e-01, 6.50000e-02, 5.00000e-02,
        1.50000e-02, 1.00000e-02, 5.00000e-03, 1.00000e-01, 7.50000e-03,
        5.00000e-03, 1.00000e-03, 3.69415e+01],
       [6.37000e+01, 1.40000e+00, 2.10000e-01, 6.50000e-02, 5.00000e-02,
        6.00000e-01, 1.00000e-02, 5.00000e-03, 7.00000e-02, 7.50000e-03,
        5.00000e-03, 0.00000e+00, 3.38775e+01],
       [6.24500e+01, 2.10000e-01, 1.00000e-01, 2.25000e-01, 2.50000e-02,
        1.50000e-02, 1.00000e-02, 0.00000e+00, 1.00000e-02, 7.50000e-03,
        5.00000e-03, 1.00000e-01, 3.68425e+01],
       [6.50000e+01, 5.00000e-01, 1.00000e-01, 5.00000e-02, 2.50000e-02,
        1.25000e-01, 1.00000e-02, 2.00000e-01, 6.50000e-02, 0.00000e+00,
        5.00000e-03, 1.00000e-03, 3.39190e+01],
       [5.83500e+01, 2.00000e-01, 2.80000e-01, 7.00000e-02, 5.00000e-02,
        1.50000e-02, 5.00000e-03, 5.00000e-03, 1.00000e-02, 5.00000e-03,
        5.00000e-03, 0.00000e+00, 4.10050e+01],
       [7.60000e+01, 5.00000e-02, 1.50000e-01, 1.50000e-01, 1.00000e-01,
        2.50000e-02, 2.50000e-02, 3.10000e+00, 0.00000e+00, 7.50000e-03,
        5.00000e-03, 6.00000e-02, 2.03275e+01]])

In [19]:
val_att

range_ric_mat = np.full((val_att.shape[0],val_att.shape[1]), None, dtype='f,f')

for iy, ix in np.ndindex(val_att.shape):
    range_ric_mat[iy, ix] = (val_att[iy, ix]/100 if val_att[iy,ix] != 0 else 0, 0.01)

print(range_ric_mat.shape)
range_ric_mat

(10, 13)

array([[(5.94000e-01, 0.05), (2.05000e-02, 0.05), (1.65000e-03, 0.05),
        (1.50000e-03, 0.05), (5.00000e-04, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (1.00000e-04, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (3.81325e-01, 0.05)],
       [(5.80000e-01, 0.05), (2.90000e-02, 0.05), (1.65000e-03, 0.05),
        (1.65000e-03, 0.05), (1.00000e-03, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (1.00000e-04, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (3.86175e-01, 0.05)],
       [(6.18000e-01, 0.05), (2.00000e-02, 0.05), (6.50000e-04, 0.05),
        (6.50000e-04, 0.05), (5.00000e-04, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (1.00000e-03, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (3.58775e-01, 0.05)],
       [(5.84000e-01, 0.05), (2.05000e-02, 0.05), (1.65000e-03, 0.05),
        (1.65000e-03, 0.05), (5.00000e-04, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (1.00000e-04, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (3.91175e-01, 0.05)],
       [(6.25000e-01, 0.05), (2.00000e-03, 0.05), (1.00000e-03, 0.05),
        (6.50000e-04, 0.05), (5.00000e-04, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (1.00000e-03, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (1.00000e-05, 0.05),
        (3.69415e-01, 0.05)],
       [(6.37000e-01, 0.05), (1.40000e-02, 0.05), (2.10000e-03, 0.05),
        (6.50000e-04, 0.05), (5.00000e-04, 0.05), (6.00000e-03, 0.05),
        (1.00000e-04, 0.05), (5.00000e-05, 0.05), (7.00000e-04, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (3.38775e-01, 0.05)],
       [(6.24500e-01, 0.05), (2.10000e-03, 0.05), (1.00000e-03, 0.05),
        (2.25000e-03, 0.05), (2.50000e-04, 0.05), (1.50000e-04, 0.05),
        (1.00000e-04, 0.05), (0.00000e+00, 0.05), (1.00000e-04, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (1.00000e-03, 0.05),
        (3.68425e-01, 0.05)],
       [(6.50000e-01, 0.05), (5.00000e-03, 0.05), (1.00000e-03, 0.05),
        (5.00000e-04, 0.05), (2.50000e-04, 0.05), (1.25000e-03, 0.05),
        (1.00000e-04, 0.05), (2.00000e-03, 0.05), (6.50000e-04, 0.05),
        (0.00000e+00, 0.05), (5.00000e-05, 0.05), (1.00000e-05, 0.05),
        (3.39190e-01, 0.05)],
       [(5.83500e-01, 0.05), (2.00000e-03, 0.05), (2.80000e-03, 0.05),
        (7.00000e-04, 0.05), (5.00000e-04, 0.05), (1.50000e-04, 0.05),
        (5.00000e-05, 0.05), (5.00000e-05, 0.05), (1.00000e-04, 0.05),
        (5.00000e-05, 0.05), (5.00000e-05, 0.05), (0.00000e+00, 0.05),
        (4.10050e-01, 0.05)],
       [(7.60000e-01, 0.05), (5.00000e-04, 0.05), (1.50000e-03, 0.05),
        (1.50000e-03, 0.05), (1.00000e-03, 0.05), (2.50000e-04, 0.05),
        (2.50000e-04, 0.05), (3.10000e-02, 0.05), (0.00000e+00, 0.05),
        (7.50000e-05, 0.05), (5.00000e-05, 0.05), (6.00000e-04, 0.05),
        (2.03275e-01, 0.05)]], dtype=[('f0', '<f4'), ('f1', '<f4')])